name: 'Dingtalk Robot Message'
description: 'dingtalk robot message for github action'
author: 'wang_xingkang@qq.com'

# Define your inputs here.
inputs:
  accessToken:
    description: 'access token'
    required: true
  type:
    description: 'message type'
    default: 'text'
  title:
    description: 'message title'
  content:
    description: 'message content'
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
outputs:
  result:
    description: "DingTalk Message Result"
branding:
  icon: "award"
  color: "green"
